name: my_pace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^18.0.1
  device_info_plus: ^11.2.0
  shared_preferences: ^2.3.4
  provider: ^6.1.2
  json_annotation: ^4.9.0
  android_alarm_manager_plus: ^4.0.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/music/
